### ISSUE TITLE
Failed to start container - "unauthorized" in a public repo

### ISSUE THREAD

**Issue by lukasz-golebiewski** [GoogleCloudPlatform/konlet#20]
I'm trying to start an instance running prometheus like this

```
gcloud beta compute instances create-with-container prometheus \
 --container-image quay.io/prometheus/prometheus:v2.1.0
```
but I keep getting this error:
`data:  "2018/02/05 14:55:36 Error: Failed to start container: Error response from daemon: {"message":"Get https://quay.io/v2/prometheus/prometheus/manifests/v2.1.0: unauthorized: Invalid Username or Password"}"   `
Is downloading public docker images supported? What am I doing wrong?

**Comment by vriesk** [comment]
Hi,

This is not intended. It looks like we've been passing the GCE-specific Oauth2 token everywhere, and this undestandably fails for a repository that does not recognize it.

I will publish a fix today, however it might take a moment to release it.

**Comment by shaneog** [comment]
Has this been fixed/released? 

I'm also seeing this just now for the Elasticsearch registry:
```
docker.elastic.co/elasticsearch/elasticsearch:5.6.8
```

**Comment by pderkowski** [comment]
Hi,

The fix has been merged, but it is not yet released. With the current version domains other than gcr.io (for public/private containers) and docker.io (public only) may not work.

**Comment by shaneog** [comment]
Thanks @pderkowski  - for now I've mirrored the image I need to GCR.

**Comment by pderkowski** [comment]
This has been fixed some time ago. Closing.
