### ISSUE TITLE
run multiple containers

### ISSUE THREAD

**Issue by frutik** [GoogleCloudPlatform/konlet#42]
I am trying to start two containers (one for my application and second one with the datadog agent to monitor the app) and getting error "Container declaration should include exactly 1 container, 2 found". What is the reason for having this limitation?

**Comment by nataliasakowska** [comment]
Hello Andrew,

unfortunately, today, to run multiple containers on COS image directly, you
would need to start the containers by writing a startup script
<https://cloud.google.com/compute/docs/startupscript> with "docker run"
commands.
We are currently assessing the use cases for supporting deployment of
multiple containers per VM using the simple method
<https://cloud.google.com/compute/docs/containers/deploying-containers> (and
its value compared to K8s solution) - and your use case is a +1 vote to
make it happen. There is no final decision yet on whether the method should
support multiple containers, but it's being actively discussed.

Regards,
Natalia Sakowska

wt., 10 lip 2018 o 13:25 Andrew Kornilov <notifications@github.com>
napisał(a):

**Comment by frutik** [comment]
thank you for the explanation!
